log /tb/CLK_FREQ_KHZ
log /tb/GUI_RUN
log /tb/clk
log /tb/reset_n
log /tb/count
log /tb/halt
log /tb/txc
log /tb/txd
log /tb/rxc
log /tb/rxd
log /tb/node0/Addr
log /tb/node0/DataIn
log /tb/node0/DataOut
log /tb/node0/NODE
log /tb/node0/RD
log /tb/node0/Update
log /tb/node0/UpdateResponse
log /tb/node0/WE
log /tb/node0/clk
log /tb/node0/count
log /tb/node0/halt
log /tb/node0/nodenum
log /tb/node0/rxc
log /tb/node0/rxc_int
log /tb/node0/rxd
log /tb/node0/rxd_int
log /tb/node0/txc
log /tb/node0/txd
